#include "cpp.h"

#include <sstream>
#include <unordered_set>

using namespace tsy::lir;

namespace tsy::codegen {

namespace {

// Prefix buffer names so source-level identifiers can never collide with
// C++ keywords, standard library symbols, or reserved names like `register`.
std::string identFor(const Buffer& b) {
    return "buf_" + b.name;
}

const Function* pickFirstTensorFunction(const Module& m) {
    for (const auto& f : m.funcs) {
        if (f->name == "main") continue;
        if (!f->params.empty()) return f.get();
    }
    return m.funcs.empty() ? nullptr : m.funcs.front().get();
}

const char* adapterSymbolFor(const std::string& primitive) {
    if (primitive == "matmul")  return "adapterMatMul";
    if (primitive == "add")     return "adapterAdd";
    if (primitive == "softmax") return "adapterSoftmax";
    if (primitive == "rmsnorm") return "adapterRMSNorm";
    return nullptr;
}

void writeHeader(std::ostream& os, const std::string& source_path) {
    os << "// AUTO-GENERATED by `tsc emit-cpp`. Do not edit.\n"
       << "// Source: " << source_path << "\n"
       << "//\n"
       << "// Links against tsy_runtime_cpu; every builtin dispatches through\n"
       << "// the CPU adapter that bridges to mini-llm-engine/ops_cpu.\n"
       << "\n"
       << "#include <cstdint>\n"
       << "#include <initializer_list>\n"
       << "#include <iostream>\n"
       << "#include <utility>\n"
       << "#include <vector>\n"
       << "\n"
       << "#include \"adapter_cpu.h\"\n"
       << "#include \"interpreter.h\"\n"
       << "\n"
       << "namespace {\n"
       << "\n"
       << "tsy::lir::NamedTensor makeBuf(const char* name,\n"
       << "                              std::initializer_list<int64_t> dims) {\n"
       << "    tsy::lir::NamedTensor t;\n"
       << "    t.name = name;\n"
       << "    t.dims.assign(dims.begin(), dims.end());\n"
       << "    std::int64_t n = 1;\n"
       << "    for (auto d : dims) n *= d;\n"
       << "    t.data.assign(static_cast<std::size_t>(n), 0.0f);\n"
       << "    return t;\n"
       << "}\n"
       << "\n"
       << "}  // namespace\n"
       << "\n";
}

}  // namespace

bool emitCppModule(std::ostream& os, const Module& m,
                   const std::string& source_path) {
    writeHeader(os, source_path);

    const Function* f = pickFirstTensorFunction(m);
    if (!f) {
        os << "int main() { return 0; }\n";
        return true;
    }

    os << "int main() {\n";

    // --- buffer instantiation ------------------------------------------
    for (const auto& b : f->buffers) {
        os << "    auto " << identFor(b) << " = makeBuf(\"" << b.name << "\", {";
        for (size_t i = 0; i < b.dims.size(); ++i) {
            if (i) os << ", ";
            os << b.dims[i];
        }
        os << "});\n";
    }
    os << "\n";

    // --- parameter fill ------------------------------------------------
    std::unordered_set<int> param_set(f->params.begin(), f->params.end());
    for (size_t i = 0; i < f->params.size(); ++i) {
        const auto& b = f->buffers[f->params[i]];
        os << "    " << identFor(b) << ".is_param = true;\n";
        os << "    tsy::lir::fillDeterministic(" << identFor(b) << ", "
           << static_cast<int>(i) << ");\n";
    }
    if (!f->params.empty()) os << "\n";

    // --- body calls ----------------------------------------------------
    for (const auto& s : f->body) {
        if (s.kind == StmtKind::Return) break;
        if (s.kind != StmtKind::Call) continue;
        const char* sym = adapterSymbolFor(s.primitive);
        if (!sym) {
            os << "    // skipped unsupported primitive: " << s.primitive << "\n";
            continue;
        }
        os << "    tsy::runtime::" << sym << "(";
        for (size_t i = 0; i < s.operand_bufs.size(); ++i) {
            if (i) os << ", ";
            os << identFor(f->buffers[s.operand_bufs[i]]);
        }
        os << ", " << identFor(f->buffers[s.result_buf]) << ");\n";
    }
    os << "\n";

    // --- result reporting ---------------------------------------------
    os << "    tsy::lir::RunResult result;\n"
       << "    result.function_name = \"" << f->name << "\";\n"
       << "    result.ok = true;\n";
    for (const auto& b : f->buffers) {
        os << "    result.buffers.push_back(std::move(" << identFor(b) << "));\n";
    }
    os << "    tsy::lir::printRunResult(std::cout, result);\n"
       << "    return 0;\n"
       << "}\n";

    return true;
}

}  // namespace tsy::codegen
